baseURL = 'http://madewithco.de/'
languageCode = 'en-us'
title = 'Made with Code'
theme = 'cactus'


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
